#! /bin/sh

# Inicia sxhkd si no está corriendo
pgrep -x sxhkd || nohup sxhkd > /dev/null 2>&1 &

# Inicia servicios necesarios
$HOME/.config/polybar/launch.sh &
setxkbmap latam &
pgrep -x picom || picom --corner-radius 20 &
nitrogen --restore &
nm-applet &

# # Detecta el número de monitores
monitors=$(xrandr --query | grep " connected" | wc -l)

# Configuración de escritorios según número de monitores
if [ "$monitors" -ne 1 ]; then
    bspc monitor eDP-1 -d 6 7 8 9 10
    bspc monitor HDMI-1 -d 1 2 3 4 5
    xrandr --output HDMI-1 --mode 1366x768 --pos 0x0 --output eDP-1 --mode 1920x1080 --pos 0x768
    bspc wm --restart
    # pgrep -x bspc wm -r || nohup bspc wm -r > /dev/null 2>&1 &
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi

# Configuración de BSPWM
bspc config border_width         2
bspc config window_gap           5
bspc config focus_follows_pointer true
bspc config focus_follows_monitor true
bspc config auto_focus           true
bspc config normal_border_color  '#333333'
bspc config focused_border_color '#1793d1'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Reglas para ventanas específicas
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a firefoxnightly desktop='^2' follow=on state=tiling
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Code desktop='^1' follow=on
bspc rule -a Alacritty desktop='^3' follow=on

